In [1]:
import torch

inputs = torch.tensor(
    [[0.43 , 0.15 , 0.89], #Your
    [0.55 , 0.87 , 0.66], #journey
    [0.57 , 0.85 , 0.64], #starts
    [0.22 , 0.58 , 0.33], #with
    [0.77 , 0.25, 0.10], #one
    [0.05 , 0.80, 0.55]]#step
)


c:\Users\sahan\anaconda3\Lib\site-packages\torch\cuda\__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]


In [3]:
d_in = inputs.shape[1]
d_out = d_in

In [4]:
torch.manual_seed(123)
W_query = torch.nn.Parameter(torch.rand(d_in,d_out) , requires_grad=False)
W_key = torch.nn.Parameter(torch.rand(d_in,d_out) , requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in,d_out) , requires_grad=False)

In [8]:
print("query:" , W_query ,"\n key:",W_key , "\n value:",W_value)

query: Parameter containing:
tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665],
        [0.1366, 0.1025, 0.1841]]) 
 key: Parameter containing:
tensor([[0.7264, 0.3153, 0.6871],
        [0.0756, 0.1966, 0.3164],
        [0.4017, 0.1186, 0.8274]]) 
 value: Parameter containing:
tensor([[0.3821, 0.6605, 0.8536],
        [0.5932, 0.6367, 0.9826],
        [0.2745, 0.6584, 0.2775]])


In [12]:
X_2 = inputs[1]


query = X_2 @ W_query
key = X_2 @ W_key
value = X_2 @ W_value
print(query)
print(key)
print(value)

tensor([0.8520, 0.4161, 1.0138])
tensor([0.7305, 0.4227, 1.1993])
tensor([0.9074, 1.3518, 1.5075])


In [13]:
queries = inputs@W_query
keys = inputs@W_key
value = inputs@W_value

print("keys shape", keys.shape)
print("queries shape", queries.shape)
print("valuess shape",value.shape)



keys shape torch.Size([6, 3])
queries shape torch.Size([6, 3])
valuess shape torch.Size([6, 3])


In [21]:
attention_score = queries@keys.T
print(attention_score)

tensor([[0.7616, 0.8765, 0.8746, 0.4349, 0.5941, 0.4877],
        [1.7872, 2.0141, 2.0091, 0.9952, 1.3538, 1.1227],
        [1.7646, 1.9901, 1.9852, 0.9834, 1.3383, 1.1091],
        [1.0664, 1.1947, 1.1916, 0.5897, 0.8004, 0.6667],
        [0.8601, 0.9968, 0.9950, 0.4947, 0.6817, 0.5516],
        [1.3458, 1.4957, 1.4915, 0.7374, 0.9968, 0.8366]])


In [28]:
import numpy as np
attention_weights = torch.softmax(attention_score/np.sqrt(3) , dim=-1)

In [29]:
attention_weights

tensor([[0.1747, 0.1866, 0.1864, 0.1446, 0.1586, 0.1491],
        [0.1862, 0.2123, 0.2117, 0.1179, 0.1450, 0.1269],
        [0.1859, 0.2118, 0.2112, 0.1184, 0.1454, 0.1273],
        [0.1798, 0.1936, 0.1932, 0.1365, 0.1542, 0.1427],
        [0.1751, 0.1895, 0.1893, 0.1418, 0.1579, 0.1465],
        [0.1837, 0.2003, 0.1998, 0.1293, 0.1501, 0.1369]])

In [31]:
attention_weights[1].sum()

tensor(1.0000)

In [32]:
context_vector = attention_weights@value

In [33]:
context_vector

tensor([[0.6692, 1.0276, 1.1106],
        [0.6864, 1.0577, 1.1389],
        [0.6860, 1.0570, 1.1383],
        [0.6738, 1.0361, 1.1180],
        [0.6711, 1.0307, 1.1139],
        [0.6783, 1.0441, 1.1252]])

In [ ]:
import torch.nn as nn

class SelfAttention1(nn.Module):
    def __init__(self , d_in , d_out):
        super().__init__()
        self.W_query = nn.Parameter(torch.rand(d_in , d_out))
        self.W_key = nn.Parameter(torch.rand(d_in , d_out))
        self.W_value = nn.Parameter(torch.rand(d_in , d_out))

    def forward(self , input):
        query = input@self.W_query   
        key = input@self.W_key
        values = input@self.W_value

        attention_score = query@key
        attention_weights = torch.softmax(attention_score/key.shape[-1]**0.5 , dim=-1) 

        context_vector = attention_weights@values

        return context_vector



       
